
-- Generated SQL for YouTube Vlogs (Long form only, Bilingual Native)
-- Fetched specifically from /videos channel tab to exclude Shorts

DELETE FROM public.posts WHERE type = 'vlog';

INSERT INTO public.posts (
  id, title, type, date, excerpt, content, link, thumbnail, read_time, status, language, created_at
) VALUES 
(
      gen_random_uuid(),
      'disneyland, paris ♡ ~ erasmus #9',
      'vlog',
      (CURRENT_DATE - INTERVAL '0 days')::date,
      'Disneyland and our 3-day Paris trip with 1 hour of sleep!',
      '',
      'https://www.youtube.com/watch?v=7J1ouQVEPus',
      'https://i.ytimg.com/vi/7J1ouQVEPus/maxresdefault.jpg',
      '21:51',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'disneyland, paris ♡ ~ erasmus #9',
      'vlog',
      (CURRENT_DATE - INTERVAL '0 days')::date,
      '1 saat uykuyla Disneyland ve 3 günlük Paris gezimiz!',
      '',
      'https://www.youtube.com/watch?v=7J1ouQVEPus',
      'https://i.ytimg.com/vi/7J1ouQVEPus/maxresdefault.jpg',
      '21:51',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'Master''s Degree while Traveling Different Countries | SCHOLARSHIP | Erasmus Mundus Master Program 🎓',
      'vlog',
      (CURRENT_DATE - INTERVAL '1 days')::date,
      'Last year I was very surprised to discover Erasmus Mundus Joint Master Program and wanted to introduce you, my graduate friends!',
      '',
      'https://www.youtube.com/watch?v=FaQnphOYFuM',
      'https://i.ytimg.com/vi/FaQnphOYFuM/maxresdefault.jpg',
      '11:19',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Gezerek Yüksek Lisans Yapmak | Yurtdışında BURSLU Master | Erasmus Mundus Joint Master Program 🎓',
      'vlog',
      (CURRENT_DATE - INTERVAL '1 days')::date,
      'Geçen sene, kendim keşfettiğimde çok şaşırdığım ve daha fazla mezun arkadaşımla tanıştırmak istediğim Erasmus Mundus Yüksek Lisans programı hakkında bilgi vermeye çalıştım!...',
      '',
      'https://www.youtube.com/watch?v=FaQnphOYFuM',
      'https://i.ytimg.com/vi/FaQnphOYFuM/maxresdefault.jpg',
      '11:19',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabanci University Sailing Trip ⛵︎ | SUSAIL | rislek vlog 7',
      'vlog',
      (CURRENT_DATE - INTERVAL '2 days')::date,
      'During my last term at Sabancı, I did the last thing which left in my to-do list, sailing training, and was eligible to participate...',
      '',
      'https://www.youtube.com/watch?v=RUUvdtXiL7c',
      'https://i.ytimg.com/vi/RUUvdtXiL7c/maxresdefault.jpg',
      '20:01',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabancı Üniversitesi Yelken Gezisi ⛵︎ | SUSAIL | rislek vlog 7',
      'vlog',
      (CURRENT_DATE - INTERVAL '2 days')::date,
      'Sabancı''da son dönemimde içimde kalan son şey olan yelken eğitimini alıp yaz gezisine katılmaya hak kazanmış oldum ⛵︎...',
      '',
      'https://www.youtube.com/watch?v=RUUvdtXiL7c',
      'https://i.ytimg.com/vi/RUUvdtXiL7c/maxresdefault.jpg',
      '20:01',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'Friends from Sabanci & Burgaz Island ♥ | rislek vlog 6',
      'vlog',
      (CURRENT_DATE - INTERVAL '3 days')::date,
      'For those...',
      '',
      'https://www.youtube.com/watch?v=updUax3p5Kc',
      'https://i.ytimg.com/vi/updUax3p5Kc/maxresdefault.jpg',
      '10:30',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabancı’dan Dostlarımla Burgazada ♥ | rislek vlog 6',
      'vlog',
      (CURRENT_DATE - INTERVAL '3 days')::date,
      'Gitmeyenler için Kalpazankaya...',
      '',
      'https://www.youtube.com/watch?v=updUax3p5Kc',
      'https://i.ytimg.com/vi/updUax3p5Kc/maxresdefault.jpg',
      '10:30',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      '6 days 3 cities & budapest/vienna/prague ~ erasmus #8',
      'vlog',
      (CURRENT_DATE - INTERVAL '4 days')::date,
      'It''s been a jam-packed 10 days, with two birthdays and 4 countries squeezed into the same week.',
      '',
      'https://www.youtube.com/watch?v=eBarsZCubOM',
      'https://i.ytimg.com/vi/eBarsZCubOM/maxresdefault.jpg',
      '15:21',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      '6 günde 3 şehir & budapeşte/viyana/prag ~ erasmus #8',
      'vlog',
      (CURRENT_DATE - INTERVAL '4 days')::date,
      'Aynı haftaya iki doğum günü 4 ülke sıkıştırdığımız dopdolu bi 10 gün oldu.',
      '',
      'https://www.youtube.com/watch?v=eBarsZCubOM',
      'https://i.ytimg.com/vi/eBarsZCubOM/maxresdefault.jpg',
      '15:21',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'halloween in spain & barcelona/madrid ~ erasmus #7',
      'vlog',
      (CURRENT_DATE - INTERVAL '5 days')::date,
      'See you in the next vlog!',
      '',
      'https://www.youtube.com/watch?v=B9TeFnDwPUw',
      'https://i.ytimg.com/vi/B9TeFnDwPUw/maxresdefault.jpg',
      '15:52',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'ispanya’da halloween & barcelona/madrid ~ erasmus #7',
      'vlog',
      (CURRENT_DATE - INTERVAL '5 days')::date,
      'Bir sonraki ülkede görüşmek...',
      '',
      'https://www.youtube.com/watch?v=B9TeFnDwPUw',
      'https://i.ytimg.com/vi/B9TeFnDwPUw/maxresdefault.jpg',
      '15:52',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'got lost & third anniversary & bratislava-vienna ~ erasmus #6',
      'vlog',
      (CURRENT_DATE - INTERVAL '6 days')::date,
      'Long story short: be careful when buying train tickets, see you in the next vlog!',
      '',
      'https://www.youtube.com/watch?v=lnrhgDPV0eA',
      'https://i.ytimg.com/vi/lnrhgDPV0eA/maxresdefault.jpg',
      '11:41',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'yanlış trene bindik & üçüncü yılımız & bratislava/viyana ~ erasmus #6',
      'vlog',
      (CURRENT_DATE - INTERVAL '6 days')::date,
      'Siz siz olun tren biletlerinizi doğru alın, bir sonraki vlog''da görüşmek üzere!',
      '',
      'https://www.youtube.com/watch?v=lnrhgDPV0eA',
      'https://i.ytimg.com/vi/lnrhgDPV0eA/maxresdefault.jpg',
      '11:41',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'a week in budapest & zoo cafe ~ erasmus #5',
      'vlog',
      (CURRENT_DATE - INTERVAL '7 days')::date,
      'After a long time, I am back with my vlogs from Erasmus!',
      '',
      'https://www.youtube.com/watch?v=UOkGfiLdmQA',
      'https://i.ytimg.com/vi/UOkGfiLdmQA/maxresdefault.jpg',
      '3:21',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'budapeşte''de bir haftam & zoo cafe ~ erasmus #5',
      'vlog',
      (CURRENT_DATE - INTERVAL '7 days')::date,
      'Uzun bir aranın ardından, erasmus vloglarımla geri döndüm!',
      '',
      'https://www.youtube.com/watch?v=UOkGfiLdmQA',
      'https://i.ytimg.com/vi/UOkGfiLdmQA/maxresdefault.jpg',
      '3:21',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'explore the city with us & first guest ~ erasmus #4',
      'vlog',
      (CURRENT_DATE - INTERVAL '8 days')::date,
      'We haven’t done any real sight-seeing before this week, so our friend’s visit was a great cause for exploring the attractions....',
      '',
      'https://www.youtube.com/watch?v=N37gwUgw8DI',
      'https://i.ytimg.com/vi/N37gwUgw8DI/maxresdefault.jpg',
      '12:10',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'bizimle budapeşte''yi keşfedin & ilk ziyaretçim ~ erasmus #4',
      'vlog',
      (CURRENT_DATE - INTERVAL '8 days')::date,
      'Bu haftadan önce Budapeşte''yi detaylu olarak gezememiştik, arkadaşımızın ziyareti güzel bir bahane oldu.',
      '',
      'https://www.youtube.com/watch?v=N37gwUgw8DI',
      'https://i.ytimg.com/vi/N37gwUgw8DI/maxresdefault.jpg',
      '12:10',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'meet my friends & sofi tukker ~ erasmus #3',
      'vlog',
      (CURRENT_DATE - INTERVAL '9 days')::date,
      'These are the memories from my erasmus experience, i still miss every second of it.',
      '',
      'https://www.youtube.com/watch?v=jca81H7Mj18',
      'https://i.ytimg.com/vi/jca81H7Mj18/maxresdefault.jpg',
      '7:40',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'arkadaşlarımla tanışın & sofi tukker ~ erasmus #3',
      'vlog',
      (CURRENT_DATE - INTERVAL '9 days')::date,
      'Geçen erasmusumdan anılar, baktıkça özlüyorum :,) Keyifli seyirler!',
      '',
      'https://www.youtube.com/watch?v=jca81H7Mj18',
      'https://i.ytimg.com/vi/jca81H7Mj18/maxresdefault.jpg',
      '7:40',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabanci University Vlog | Winter 2022 | It snowed! | rislek vlog 5',
      'vlog',
      (CURRENT_DATE - INTERVAL '10 days')::date,
      'I wanted to remember this day, which makes me happy every time I look at it :) See you again in snowy vlogs!',
      '',
      'https://www.youtube.com/watch?v=Iw-Jkqcz5jc',
      'https://i.ytimg.com/vi/Iw-Jkqcz5jc/maxresdefault.jpg',
      '15:48',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabancı Üniversitesi Vlog ❅ | Kış 2022 | Kar Gören İzmirli | rislek vlog 5',
      'vlog',
      (CURRENT_DATE - INTERVAL '10 days')::date,
      'İçimizi ısıtan diyemem ama baktıkça mutlu olduğum bu günü bir hatırlayalım istedim:) Tekrar karlı vloglarda görüşmek...',
      '',
      'https://www.youtube.com/watch?v=Iw-Jkqcz5jc',
      'https://i.ytimg.com/vi/Iw-Jkqcz5jc/maxresdefault.jpg',
      '15:48',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'last new year''s eve | how did we enter 2022? | rislek vlog 4',
      'vlog',
      (CURRENT_DATE - INTERVAL '11 days')::date,
      'As we are coming to the end of the year, let''s remember how we entered this year :) Kisses!',
      '',
      'https://www.youtube.com/watch?v=yp9k5jq7TSU',
      'https://i.ytimg.com/vi/yp9k5jq7TSU/maxresdefault.jpg',
      '14:13',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Geçen Yılbaşı🎄| 2022''ye nasıl girdik? | rislek vlog 4',
      'vlog',
      (CURRENT_DATE - INTERVAL '11 days')::date,
      'Sene sonuna yaklaşırken bu yıla nasıl girdiğimizi bir hatırlayalım:) Öptüm!',
      '',
      'https://www.youtube.com/watch?v=yp9k5jq7TSU',
      'https://i.ytimg.com/vi/yp9k5jq7TSU/maxresdefault.jpg',
      '14:13',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'i swam in a swan lake & balaton~ erasmus #2',
      'vlog',
      (CURRENT_DATE - INTERVAL '12 days')::date,
      'Highlights from our first trip with ESN :) Thank you!',
      '',
      'https://www.youtube.com/watch?v=9hCvFl1ZOFo',
      'https://i.ytimg.com/vi/9hCvFl1ZOFo/maxresdefault.jpg',
      '3:09',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'kuğulu gölde yüzdüm & balaton ~ erasmus #2',
      'vlog',
      (CURRENT_DATE - INTERVAL '12 days')::date,
      'ESN gezimizden kısa kesitler :) İyi izlemeler!',
      '',
      'https://www.youtube.com/watch?v=9hCvFl1ZOFo',
      'https://i.ytimg.com/vi/9hCvFl1ZOFo/maxresdefault.jpg',
      '3:09',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'my first week in budapest ~ erasmus #1',
      'vlog',
      (CURRENT_DATE - INTERVAL '13 days')::date,
      'I wanted to thank ESN BME for organizing this amazing orientation week where i had a chance to meet lots of lovely people!',
      '',
      'https://www.youtube.com/watch?v=P2kTKg1JQEI',
      'https://i.ytimg.com/vi/P2kTKg1JQEI/maxresdefault.jpg',
      '3:34',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'budapeşte''de ilk haftam ~ erasmus #1',
      'vlog',
      (CURRENT_DATE - INTERVAL '13 days')::date,
      'ESN BME''ye böyle bir oryantasyon/organizasyon düzenledikleri için çok teşekkür ederim, ilk haftamdan bir sürü yabancı arkadaş...',
      '',
      'https://www.youtube.com/watch?v=P2kTKg1JQEI',
      'https://i.ytimg.com/vi/P2kTKg1JQEI/maxresdefault.jpg',
      '3:34',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'formula 1 with my bf | Grand Prix TR 2021 | rislek vlog 3',
      'vlog',
      (CURRENT_DATE - INTERVAL '14 days')::date,
      'If you know anything about Formula, I''m waiting for interesting details in the comments, I hope you enjoy it, kisses.',
      '',
      'https://www.youtube.com/watch?v=FD0Ef5ruH1g',
      'https://i.ytimg.com/vi/FD0Ef5ruH1g/maxresdefault.jpg',
      '13:33',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'her masada varız: formula 1 | Grand Prix TR 2021 | rislek vlog 3',
      'vlog',
      (CURRENT_DATE - INTERVAL '14 days')::date,
      'Formula 1 ayağımıza gelir de gitmez miyiz dedik ve engin(!) yorumlarımızla iki günümüzü kayda aldık, Cem de her zamanki...',
      '',
      'https://www.youtube.com/watch?v=FD0Ef5ruH1g',
      'https://i.ytimg.com/vi/FD0Ef5ruH1g/maxresdefault.jpg',
      '13:33',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabanci University Orientation Week 2021 | My First Week | Dorm Room | rislek vlog 2',
      'vlog',
      (CURRENT_DATE - INTERVAL '15 days')::date,
      'Hey!',
      '',
      'https://www.youtube.com/watch?v=pGmBRqw9vjg',
      'https://i.ytimg.com/vi/pGmBRqw9vjg/maxresdefault.jpg',
      '15:48',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Sabancı Üniversitesi Oryantasyon 2021 | Okulda İlk Haftam | Yurda Yerleşme | rislek vlog 2',
      'vlog',
      (CURRENT_DATE - INTERVAL '15 days')::date,
      'Hop!',
      '',
      'https://www.youtube.com/watch?v=pGmBRqw9vjg',
      'https://i.ytimg.com/vi/pGmBRqw9vjg/maxresdefault.jpg',
      '15:48',
      'published',
      'tr',
      NOW()
    ),
(
      gen_random_uuid(),
      'My Sister''s Engagement Party | Çeşme | rislek vlog 1 [ENG-SUB]',
      'vlog',
      (CURRENT_DATE - INTERVAL '16 days')::date,
      'Hello everyone :)  I realized I''ve missed summer so much that I wanted to share this video from my sister''s engagement party,...',
      '',
      'https://www.youtube.com/watch?v=BzZJdgrPJr0',
      'https://i.ytimg.com/vi/BzZJdgrPJr0/maxresdefault.jpg',
      '21:47',
      'published',
      'en',
      NOW()
    ),
(
      gen_random_uuid(),
      'Ablamın Nişanı ♡ | Çeşme |  rislek vlog 1',
      'vlog',
      (CURRENT_DATE - INTERVAL '16 days')::date,
      'Herkese miriba :) Yazı özlediğimi fark edip geçen yaz bahçemizde yaptığımız nişan günümüze ışınladım bizi, umarım...',
      '',
      'https://www.youtube.com/watch?v=BzZJdgrPJr0',
      'https://i.ytimg.com/vi/BzZJdgrPJr0/maxresdefault.jpg',
      '21:47',
      'published',
      'tr',
      NOW()
    )
ON CONFLICT DO NOTHING;
    